In [1]:
import os
import pandas as pd
import numpy as np
from datetime import datetime

In [58]:
os.getcwd()

'/Users/caseyh/Desktop/footyfootyfooty/data_wrangling'

In [59]:
seasons = sorted(os.listdir('/Users/caseyh/Desktop/footyfootyfooty/round_results/'))[-25:-1]

In [60]:
player_files = sorted(os.listdir('/Users/caseyh/Desktop/footyfootyfooty/player_stats/'))[-24:]

In [61]:
player_data = pd.DataFrame({})
for file in player_files:
    path = '/Users/caseyh/Desktop/footyfootyfooty/player_stats/'
    tmp = pd.read_csv(path + file)
    player_data = pd.concat([player_data, tmp])
player_data = player_data.reset_index(drop=True)

In [62]:
season_data = pd.DataFrame({})
for season in seasons:
    path = '/Users/caseyh/Desktop/footyfootyfooty/round_results/'
    tmp = pd.read_csv(path + season)
    season_data = pd.concat([season_data, tmp])
season_data = season_data.reset_index(drop=True)

season_data = season_data.dropna()

In [63]:
season_data['Date'] = season_data['Date'].str.extract(r'(\d{1,2} \w{3})')
season_data['Date'] = season_data['Date'] + ' ' + season_data['year'].apply(str)

In [64]:
def rearrange_date(x):
    return datetime.strptime(x, '%d %b %Y')

In [65]:
season_data['Date'] = season_data['Date'].apply(lambda x: rearrange_date(x))

In [66]:
teams = ['RCH', 'GEE', 'NTH', 'POR', 'GCS', 'MEL', 'GWS', 'HAW', 'STK',
       'CAR', 'BRL', 'COL', 'ADE', 'FRE', 'WBD', 'SYD', 'ESS', 'WCE']

In [67]:
# rearrange game table into both sides (double)
output = pd.DataFrame({})
for season in season_data['year'].unique():
    for r in season_data['round'].unique():
        r_season = season_data[(season_data['round'] == r)&(season_data['year']==season)]
        for i,j in [('Home','Away'), ('Away', 'Home')]:
            rounds = pd.DataFrame({})
            rounds['venue'] = r_season['Venue']
            rounds['team'] = r_season[f'{i}']
            rounds['opponent'] = r_season[f'{j}']
            rounds['won'] = np.select([r_season[f'{i} Score'] > r_season[f'{j} Score']], [1],0)
            rounds['loss'] = np.select([r_season[f'{i} Score'] < r_season[f'{j} Score']], [1],0)
            rounds['draw'] = np.select([r_season[f'{i} Score'] == r_season[f'{j} Score']], [1],0)
            rounds['pf'] = r_season[f'{i} Score']
            rounds['pa'] = r_season[f'{j} Score']
            rounds['margin'] = r_season[f'{i} Score'] - r_season[f'{j} Score']
            rounds['year'] = season
            rounds['round'] = r
            rounds['at_home'] = i
            rounds['date'] = r_season['Date']
            
            
            output = pd.concat([output, rounds])

output = output.reset_index(drop = True)
output['round'] = output['round'].str.replace('Round ','R')

In [68]:
output

,venue,team,opponent,won,loss,draw,pf,pa,margin,year,round,at_home,date
0,MCG,MEL,RCH,0,1,0,92.0,94.0,-2.0,2000,R1,Home,2000-03-08
1,Marvel Stadium,ESS,POR,1,0,0,156.0,62.0,94.0,2000,R1,Home,2000-03-09
2,MCG,NTH,WCE,0,1,0,111.0,154.0,-43.0,2000,R1,Home,2000-03-10
3,Domain Stadium,FRE,GEE,0,1,0,107.0,129.0,-22.0,2000,R1,Home,2000-03-11
4,AAMI Stadium,ADE,WBD,0,1,0,108.0,131.0,-23.0,2000,R1,Home,2000-03-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9335,Adelaide Oval,RCH,POR,0,0,0,NaN,NaN,NaN,2023,R24,Away,2023-08-25
9336,SCG,MEL,SYD,0,0,0,NaN,NaN,NaN,2023,R24,Away,2023-08-25
9337,Blundstone Arena,GCS,NTH,0,0,0,NaN,NaN,NaN,2023,R24,Away,2023-08-25
9338,MCG,FRE,HAW,0,0,0,NaN,NaN,NaN,2023,R24,Away,2023-08-25
9339,GMHBA Stadium,WBD,GEE,0,0,0,NaN,NaN,NaN,2023,R24,Away,2023-08-25

In [69]:
output['at_home'] = output['at_home'] == 'Home'

In [70]:
output['round'] = pd.Categorical(output['round'], ['R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11',
       'R12', 'R13', 'R14', 'R15', 'R16', 'R17', 'R18', 'R19', 'R20',
       'R21', 'R22', 'R23', 'R24','EF', 'QF', 'SF', 'PF', 'GF.0','GF'])
output = output.sort_values(['year','round'])

In [71]:
home_games = output[output['at_home']].reset_index(drop=True)
away_games = output[~output['at_home']].reset_index(drop=True)

In [72]:
home_games['game_id'] = home_games.at_home.rank(method="first", ascending=False).astype(int)
away_games['game_id'] = away_games.at_home.rank(method="first", ascending=False).astype(int)

In [73]:
games = pd.concat([home_games,away_games]).sort_values('game_id').reset_index(drop=True)

In [74]:
games['round'] = pd.Categorical(games['round'], ['R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11',
       'R12', 'R13', 'R14', 'R15', 'R16', 'R17', 'R18', 'R19', 'R20',
       'R21', 'R22', 'R23', 'R24','EF', 'QF', 'SF', 'PF', 'GF.0','GF'])
games = games.sort_values(['year','round'])

## Team Data
Aggregate player stats to get team stats

In [75]:
team_data['round'] = pd.Categorical(team_data['round'], ['R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11',
       'R12', 'R13', 'R14', 'R15', 'R16', 'R17', 'R18', 'R19', 'R20',
       'R21', 'R22', 'R23', 'R24','EF', 'QF', 'SF', 'PF', 'GF.0','GF'])
team_data = team_data.sort_values(['year','round'])

In [76]:
team_data = player_data.groupby(['year','round','team']).sum().reset_index()

In [77]:
output.loc[(output['pf']==output['pa'])&(output['round']=='GF'),'round'] = 'GF.0'

In [78]:
team_data.loc[(team_data['round']=='GF')&(team_data['year']==2010),'round']='GF.0'

In [79]:
team_data.loc[(team_data['round']=='GF.1'),'round']='GF.1'

In [80]:
games = games.merge(team_data, on=['year','round','team'])

In [82]:
# add rushed behind to behinds (only includes player behinds)
games['rushed behinds'] = games['pf'] - 6 * games['Goals'] - games['Behinds']

In [84]:
games['Behinds'] = games['Behinds'] + games['rushed behinds']

In [85]:
non_feature_cols = ['team', 'date', 'at_home', 'game_id', 'round', 'venue', 'opponent', 'year']
games = games.rename(columns={col: 'f_' + col for col in games if col not in non_feature_cols})

In [102]:
features = games[['date', 'game_id', 'team', 'opponent', 'venue', 'at_home']].copy()

In [107]:
games

,venue,team,opponent,f_won,f_loss,f_draw,f_pf,f_pa,f_margin,year,round,at_home,date,game_id,f_Disposals,f_Kicks,f_Handballs,f_Goals,f_Behinds,f_Marks,f_Clearances,f_Tackles,f_Contested Possessions,f_Uncontested Possessions,f_Hit Outs,f_Contested Marks,f_Marks Inside 50,f_Goal Assists,f_Frees,f_Frees Against,f_Inside 50s,f_Rebounds,f_Clangers,f_One Percenters,f_Bounces,f_Brownlow Votes,f_rushed behinds
0,MCG,MEL,RCH,0,1,0,92.0,94.0,-2.0,2000,R1,True,2000-03-08,1,272.0,183.0,89.0,13.0,14.0,59.0,37.0,28.0,123.0,145.0,33.0,14.0,10.0,0.0,27.0,36.0,62.0,31.0,39.0,17.0,16.0,0.0,2.0
1,MCG,RCH,MEL,1,0,0,94.0,92.0,2.0,2000,R1,False,2000-03-08,1,275.0,202.0,73.0,14.0,10.0,62.0,39.0,37.0,126.0,139.0,34.0,11.0,4.0,0.0,36.0,27.0,51.0,39.0,27.0,27.0,9.0,6.0,1.0
2,Marvel Stadium,POR,ESS,0,1,0,62.0,156.0,-94.0,2000,R1,False,2000-03-09,2,328.0,194.0,134.0,8.0,14.0,90.0,40.0,24.0,113.0,220.0,29.0,10.0,11.0,0.0,15.0,33.0,48.0,34.0,57.0,20.0,15.0,0.0,3.0
3,Marvel Stadium,ESS,POR,1,0,0,156.0,62.0,94.0,2000,R1,True,2000-03-09,2,349.0,213.0,136.0,24.0,12.0,79.0,28.0,38.0,125.0,217.0,27.0,12.0,18.0,0.0,33.0,15.0,66.0,33.0,42.0,32.0,12.0,6.0,1.0
4,MCG,NTH,WCE,0,1,0,111.0,154.0,-43.0,2000,R1,True,2000-03-10,3,303.0,204.0,99.0,16.0,15.0,70.0,36.0,20.0,145.0,164.0,33.0,13.0,9.0,0.0,28.0,22.0,55.0,41.0,26.0,29.0,18.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9223,GMHBA Stadium,ESS,GEE,0,1,0,45.0,122.0,-77.0,2023,R18,False,2023-07-15,4614,358.0,215.0,143.0,7.0,3.0,82.0,35.0,53.0,128.0,199.0,35.0,4.0,5.0,6.0,21.0,16.0,28.0,46.0,62.0,46.0,8.0,0.0,2.0
9224,Marvel Stadium,HAW,NTH,1,0,0,88.0,40.0,48.0,2023,R18,False,2023-07-16,4615,438.0,211.0,227.0,12.0,16.0,89.0,37.0,53.0,149.0,291.0,39.0,8.0,9.0,11.0,17.0,25.0,70.0,34.0,55.0,52.0,13.0,0.0,3.0
9225,Marvel Stadium,NTH,HAW,0,1,0,40.0,88.0,-48.0,2023,R18,True,2023-07-16,4615,378.0,219.0,159.0,6.0,4.0,107.0,35.0,74.0,126.0,244.0,32.0,10.0,3.0,3.0,25.0,17.0,41.0,57.0,58.0,60.0,8.0,0.0,3.0
9226,Optus Stadium,WCE,RCH,0,1,0,60.0,98.0,-38.0,2023,R18,True,2023-07-16,4616,339.0,195.0,144.0,8.0,12.0,80.0,41.0,55.0,126.0,214.0,26.0,10.0,12.0,4.0,15.0,12.0,50.0,35.0,48.0,42.0,5.0,0.0,1.0
9227,Optus Stadium,RCH,WCE,1,0,0,98.0,60.0,38.0,2023,R18,False,2023-07-16,4616,345.0,191.0,154.0,14.0,14.0,76.0,38.0,53.0,124.0,214.0,59.0,12.0,22.0,12.0,12.0,15.0,51.0,42.0,50.0,37.0,8.0,0.0,3.0

In [108]:
match_results = games[['game_id', 'team', 'opponent', 'f_margin']]

## Exponential rolling avergae

In [89]:
# Define a function which returns a DataFrame with the expontential moving average for each numeric stat
def create_exp_weighted_avgs(df, span):
    # Create a copy of the df with only the game id and the team - we will add cols to this df
    ema_features = df[['game_id', 'team']].copy()

    feature_names = [col for col in df.columns if col.startswith('f_')] # Get a list of columns we will iterate over

    for feature_name in feature_names:
        feature_ema = (df.groupby('team')[feature_name]
                         .transform(lambda row: (row.ewm(span=span)
                                                    .mean()
                                                    .shift(1))))
        ema_features[feature_name] = feature_ema

    return ema_features

In [100]:
features_rolling_averages = create_exp_weighted_avgs(games, 10)

In [105]:
features = pd.merge(features, features_rolling_averages, on=['game_id', 'team'])

## Form between Teams

In [112]:
form_btwn_teams = games[['game_id', 'team', 'opponent', 'f_margin']].copy()

In [113]:
form_btwn_teams['f_form_margin_btwn_teams'] = (games.groupby(['team', 'opponent'])['f_margin'].transform(lambda row: row.rolling(5).mean().shift())
                                                .fillna(0))

In [115]:
form_btwn_teams['f_form_past_5_btwn_teams'] = \
(games.assign(win=lambda df: df.apply(lambda row: 1 if row.f_margin > 0 else 0, axis='columns'))
              .groupby(['team', 'opponent'])['win']
              .transform(lambda row: row.rolling(5).mean().shift() * 5)
              .fillna(0))

In [118]:
# Merge to our features df
features = pd.merge(features, form_btwn_teams.drop(columns=['f_margin']), on=['game_id', 'team', 'opponent'])

In [119]:
features

,date,game_id,team,opponent,venue,at_home,f_won,f_loss,f_draw,f_pf,f_pa,f_margin,f_Disposals,f_Kicks,f_Handballs,f_Goals,f_Behinds,f_Marks,f_Clearances,f_Tackles,f_Contested Possessions,f_Uncontested Possessions,f_Hit Outs,f_Contested Marks,f_Marks Inside 50,f_Goal Assists,f_Frees,f_Frees Against,f_Inside 50s,f_Rebounds,f_Clangers,f_One Percenters,f_Bounces,f_Brownlow Votes,f_rushed behinds,f_form_margin_btwn_teams,f_form_past_5_btwn_teams
0,2000-03-08,1,MEL,RCH,MCG,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1,2000-03-08,1,RCH,MEL,MCG,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2,2000-03-09,2,POR,ESS,Marvel Stadium,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,2000-03-09,2,ESS,POR,Marvel Stadium,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
4,2000-03-10,3,NTH,WCE,MCG,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9223,2023-07-15,4614,ESS,GEE,GMHBA Stadium,False,0.553173,0.446827,2.154891e-07,86.969845,83.650492,3.319353,377.492249,220.621690,156.870559,12.685813,10.854967,103.684211,33.385929,56.236414,132.995589,237.686386,36.458967,10.882043,13.425459,9.121104,18.041526,15.266884,50.001103,41.847632,52.096075,46.261819,6.482063,0.086676,2.398757,-46.6,0.0
9224,2023-07-16,4615,HAW,NTH,Marvel Stadium,False,0.248618,0.751261,1.212236e-04,71.264825,94.591018,-23.326193,385.475739,199.714720,185.761020,10.249758,9.766277,84.325428,34.192709,60.041230,136.433193,243.811693,40.380212,8.716184,9.485825,7.852273,17.414271,17.706913,51.084639,41.607450,58.345878,43.735675,10.117083,0.088476,2.417026,16.4,4.0
9225,2023-07-16,4615,NTH,HAW,Marvel Stadium,True,0.022827,0.977161,1.192419e-05,72.386552,113.673851,-41.287300,356.101750,196.148163,159.953587,10.718967,8.072750,86.078614,35.449492,57.938208,131.628661,219.688020,41.504571,11.075707,8.232891,8.289595,14.526454,18.111278,44.578704,43.550994,59.912810,43.681308,4.776586,0.070517,2.416707,-16.4,1.0
9226,2023-07-16,4616,WCE,RCH,Optus Stadium,True,0.012748,0.987252,2.502104e-17,51.541471,128.121609,-76.580138,337.083249,193.327039,143.756209,7.549187,6.246346,92.372003,34.414727,61.947624,114.692150,213.801024,35.518312,7.971075,6.567238,5.105483,16.722319,17.475404,37.983710,40.551385,53.268337,37.178341,4.909890,0.036322,1.860556,-42.6,1.0
9227,2023-07-16,4616,RCH,WCE,Optus Stadium,False,0.600176,0.388101,1.172251e-02,81.836840,86.058253,-4.221413,355.917302,214.728770,141.188532,11.565784,12.442139,79.036473,37.044430,59.571707,138.417172,205.791057,44.525815,10.278012,12.421192,7.734935,14.391534,18.301593,52.746953,44.702444,68.302382,57.601030,7.178827,0.140682,2.920697,42.6,4.0

## Single Row

In [120]:
games

,venue,team,opponent,f_won,f_loss,f_draw,f_pf,f_pa,f_margin,year,round,at_home,date,game_id,f_Disposals,f_Kicks,f_Handballs,f_Goals,f_Behinds,f_Marks,f_Clearances,f_Tackles,f_Contested Possessions,f_Uncontested Possessions,f_Hit Outs,f_Contested Marks,f_Marks Inside 50,f_Goal Assists,f_Frees,f_Frees Against,f_Inside 50s,f_Rebounds,f_Clangers,f_One Percenters,f_Bounces,f_Brownlow Votes,f_rushed behinds
0,MCG,MEL,RCH,0,1,0,92.0,94.0,-2.0,2000,R1,True,2000-03-08,1,272.0,183.0,89.0,13.0,14.0,59.0,37.0,28.0,123.0,145.0,33.0,14.0,10.0,0.0,27.0,36.0,62.0,31.0,39.0,17.0,16.0,0.0,2.0
1,MCG,RCH,MEL,1,0,0,94.0,92.0,2.0,2000,R1,False,2000-03-08,1,275.0,202.0,73.0,14.0,10.0,62.0,39.0,37.0,126.0,139.0,34.0,11.0,4.0,0.0,36.0,27.0,51.0,39.0,27.0,27.0,9.0,6.0,1.0
2,Marvel Stadium,POR,ESS,0,1,0,62.0,156.0,-94.0,2000,R1,False,2000-03-09,2,328.0,194.0,134.0,8.0,14.0,90.0,40.0,24.0,113.0,220.0,29.0,10.0,11.0,0.0,15.0,33.0,48.0,34.0,57.0,20.0,15.0,0.0,3.0
3,Marvel Stadium,ESS,POR,1,0,0,156.0,62.0,94.0,2000,R1,True,2000-03-09,2,349.0,213.0,136.0,24.0,12.0,79.0,28.0,38.0,125.0,217.0,27.0,12.0,18.0,0.0,33.0,15.0,66.0,33.0,42.0,32.0,12.0,6.0,1.0
4,MCG,NTH,WCE,0,1,0,111.0,154.0,-43.0,2000,R1,True,2000-03-10,3,303.0,204.0,99.0,16.0,15.0,70.0,36.0,20.0,145.0,164.0,33.0,13.0,9.0,0.0,28.0,22.0,55.0,41.0,26.0,29.0,18.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9223,GMHBA Stadium,ESS,GEE,0,1,0,45.0,122.0,-77.0,2023,R18,False,2023-07-15,4614,358.0,215.0,143.0,7.0,3.0,82.0,35.0,53.0,128.0,199.0,35.0,4.0,5.0,6.0,21.0,16.0,28.0,46.0,62.0,46.0,8.0,0.0,2.0
9224,Marvel Stadium,HAW,NTH,1,0,0,88.0,40.0,48.0,2023,R18,False,2023-07-16,4615,438.0,211.0,227.0,12.0,16.0,89.0,37.0,53.0,149.0,291.0,39.0,8.0,9.0,11.0,17.0,25.0,70.0,34.0,55.0,52.0,13.0,0.0,3.0
9225,Marvel Stadium,NTH,HAW,0,1,0,40.0,88.0,-48.0,2023,R18,True,2023-07-16,4615,378.0,219.0,159.0,6.0,4.0,107.0,35.0,74.0,126.0,244.0,32.0,10.0,3.0,3.0,25.0,17.0,41.0,57.0,58.0,60.0,8.0,0.0,3.0
9226,Optus Stadium,WCE,RCH,0,1,0,60.0,98.0,-38.0,2023,R18,True,2023-07-16,4616,339.0,195.0,144.0,8.0,12.0,80.0,41.0,55.0,126.0,214.0,26.0,10.0,12.0,4.0,15.0,12.0,50.0,35.0,48.0,42.0,5.0,0.0,1.0
9227,Optus Stadium,RCH,WCE,1,0,0,98.0,60.0,38.0,2023,R18,False,2023-07-16,4616,345.0,191.0,154.0,14.0,14.0,76.0,38.0,53.0,124.0,214.0,59.0,12.0,22.0,12.0,12.0,15.0,51.0,42.0,50.0,37.0,8.0,0.0,3.0

In [122]:
# Get each match on single rows
single_row_df = (games[['game_id', 'team', 'f_Inside 50s', 'f_Rebounds', 'f_Disposals', 'at_home', ]]
                    .query('at_home == 1')
                    .rename(columns={'team': 'home_team', 'f_Inside 50s': 'f_Inside 50s_home', 'f_Rebounds': 'f_Rebounds_home', 'f_Disposals': 'f_Disposals_home'})
                    .drop(columns='at_home')
                    .pipe(pd.merge, games[['game_id', 'team', 'f_Inside 50s', 'f_Rebounds', 'f_Disposals', 'at_home']]
                                    .query('at_home == 0')
                                    .rename(columns={'team': 'away_team', 'f_Inside 50s': 'f_Inside 50s_away', 'f_Rebounds': 'f_Rebounds_away', 'f_Disposals': 'f_Disposals_away'})
                                    .drop(columns='at_home'), on='game_id'))

In [123]:
single_row_df

,game_id,home_team,f_Inside 50s_home,f_Rebounds_home,f_Disposals_home,away_team,f_Inside 50s_away,f_Rebounds_away,f_Disposals_away
0,1,MEL,62.0,31.0,272.0,RCH,51.0,39.0,275.0
1,2,ESS,66.0,33.0,349.0,POR,48.0,34.0,328.0
2,3,NTH,55.0,41.0,303.0,WCE,67.0,34.0,341.0
3,4,FRE,55.0,36.0,337.0,GEE,59.0,29.0,301.0
4,5,ADE,55.0,32.0,261.0,WBD,59.0,38.0,332.0
...,...,...,...,...,...,...,...,...,...
4609,4612,CAR,59.0,50.0,353.0,POR,62.0,41.0,361.0
4610,4613,ADE,54.0,49.0,354.0,GWS,60.0,44.0,358.0
4611,4614,GEE,64.0,20.0,389.0,ESS,28.0,46.0,358.0
4612,4615,NTH,41.0,57.0,378.0,HAW,70.0,34.0,438.0
4613,4616,WCE,50.0,35.0,339.0,RCH,51.0,42.0,345.0

In [141]:
single_row_df = single_row_df.assign(f_I50_efficiency_home=lambda df: df.f_Rebounds_away / df['f_Inside 50s_home'],
                                    f_I50_efficiency_away=lambda df: df.f_Rebounds_home / df['f_Inside 50s_away'])

feature_efficiency_cols = ['f_I50_efficiency_home', 'f_I50_efficiency_away']

In [143]:
# Now let's create an Expontentially Weighted Moving Average for these features - we will need to reshape our DataFrame to do this
efficiency_features_multi_row = (single_row_df[['game_id', 'home_team'] + feature_efficiency_cols]
                                    .rename(columns={
                                        'home_team': 'team',
                                        'f_I50_efficiency_home': 'f_I50_efficiency',
                                        'f_I50_efficiency_away': 'f_I50_efficiency_opponent',
                                    })
                                    .append((single_row_df[['game_id', 'away_team'] + feature_efficiency_cols]
                                                 .rename(columns={
                                                     'away_team': 'team',
                                                     'f_I50_efficiency_home': 'f_I50_efficiency_opponent',
                                                     'f_I50_efficiency_away': 'f_I50_efficiency',
                                                 })), sort=True)
                                    .sort_values(by='game_id')
                                    .reset_index(drop=True))

efficiency_features = efficiency_features_multi_row[['game_id', 'team']].copy()
feature_efficiency_cols = ['f_I50_efficiency', 'f_I50_efficiency_opponent']

for feature in feature_efficiency_cols:
    efficiency_features[feature] = (efficiency_features_multi_row.groupby('team')[feature]
                                        .transform(lambda row: row.ewm(span=10).mean().shift(1)))

/var/folders/ww/qljj89hs53b_mxcs8j00tyfw0000gn/T/ipykernel_87885/550343861.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  efficiency_features_multi_row = (single_row_df[['game_id', 'home_team'] + feature_efficiency_cols]

In [144]:
# Get feature efficiency df back onto single rows
efficiency_features = pd.merge(efficiency_features, games[['game_id', 'team', 'at_home']], on=['game_id', 'team'])
efficiency_features_single_row = (efficiency_features.query('at_home == 1')
                                    .rename(columns={
                                        'team': 'home_team', 
                                        'f_I50_efficiency': 'f_I50_efficiency_home',
                                        'f_I50_efficiency_opponent': 'f_R50_efficiency_home'})
                                    .drop(columns='at_home')
                                    .pipe(pd.merge, (efficiency_features.query('at_home == 0')
                                                        .rename(columns={
                                                            'team': 'away_team',
                                                            'f_I50_efficiency': 'f_I50_efficiency_away',
                                                            'f_I50_efficiency_opponent': 'f_R50_efficiency_away'})
                                                        .drop(columns='at_home')), on='game_id'))

## Elo Rating

In [151]:
# Define a function which finds the elo for each team in each game and returns a dictionary with the game ID as a key and the
# elos as the key's value, in a list. It also outputs the probabilities and a dictionary of the final elos for each team
def elo_applier(df, k_factor):
    # Initialise a dictionary with default elos for each team
    elo_dict = {team: 1500 for team in df['team'].unique()}
    elos, elo_probs = {}, {}

    # Get a home and away dataframe so that we can get the teams on the same row
    home_df = df.loc[df.at_home == 1, ['team', 'game_id', 'f_margin', 'at_home']].rename(columns={'team': 'home_team'})
    away_df = df.loc[df.at_home == 0, ['team', 'game_id']].rename(columns={'team': 'away_team'})

    df = (pd.merge(home_df, away_df, on='game_id')
            .sort_values(by='game_id')
            .drop_duplicates(subset='game_id', keep='first')
            .reset_index(drop=True))

    # Loop over the rows in the DataFrame
    for index, row in df.iterrows():
        # Get the Game ID
        game_id = row['game_id']

        # Get the margin
        margin = row['f_margin']

        # If the game already has the elos for the home and away team in the elos dictionary, go to the next game
        if game_id in elos.keys():
            continue

        # Get the team and opposition
        home_team = row['home_team']
        away_team = row['away_team']

        # Get the team and opposition elo score
        home_team_elo = elo_dict[home_team]
        away_team_elo = elo_dict[away_team]

        # Calculated the probability of winning for the team and opposition
        prob_win_home = 1 / (1 + 10**((away_team_elo - home_team_elo) / 400))
        prob_win_away = 1 - prob_win_home

        # Add the elos and probabilities our elos dictionary and elo_probs dictionary based on the Game ID
        elos[game_id] = [home_team_elo, away_team_elo]
        elo_probs[game_id] = [prob_win_home, prob_win_away]

        # Calculate the new elos of each team
        if margin > 0: # Home team wins; update both teams' elo
            new_home_team_elo = home_team_elo + k_factor*(1 - prob_win_home)
            new_away_team_elo = away_team_elo + k_factor*(0 - prob_win_away)
        elif margin < 0: # Away team wins; update both teams' elo
            new_home_team_elo = home_team_elo + k_factor*(0 - prob_win_home)
            new_away_team_elo = away_team_elo + k_factor*(1 - prob_win_away)
        elif margin == 0: # Drawn game' update both teams' elo
            new_home_team_elo = home_team_elo + k_factor*(0.5 - prob_win_home)
            new_away_team_elo = away_team_elo + k_factor*(0.5 - prob_win_away)

        # Update elos in elo dictionary
        elo_dict[home_team] = new_home_team_elo
        elo_dict[away_team] = new_away_team_elo

    return elos, elo_probs, elo_dict

In [152]:
# Use the elo applier function to get the elos and elo probabilities for each game - we will map these later
elos, probs, elo_dict = elo_applier(games, 30)

In [163]:
one_line_cols = ['game_id', 'team', 'at_home'] + [col for col in features if col.startswith('f_')]

# Get all features onto individual rows for each match
features_one_line = (features.loc[features.at_home == 1, one_line_cols]
                     .rename(columns={'team': 'home_team'})
                     .drop(columns='at_home')
                     .pipe(pd.merge, (features.loc[features.at_home == 0, one_line_cols]
                                              .drop(columns='at_home')
                                              .rename(columns={'team': 'away_team'})
                                              .rename(columns={col: col+'_away' for col in features.columns if col.startswith('f_')})), on='game_id')
                    .drop(columns=['f_form_margin_btwn_teams_away', 'f_form_past_5_btwn_teams_away']))

# Add our created features - elo, efficiency etc.
features_one_line = (features_one_line.assign(f_elo_home=lambda df: df.game_id.map(elos).apply(lambda x: x[0]),
                                            f_elo_away=lambda df: df.game_id.map(elos).apply(lambda x: x[1]))
                                      .pipe(pd.merge, efficiency_features_single_row, on=['game_id', 'home_team', 'away_team'])
                                      .pipe(pd.merge, games.loc[games.at_home == 1, ['game_id', 'date', 'round', 'venue']], on=['game_id'])
                                      .dropna()
                                      .reset_index(drop=True)
                                      .assign(season=lambda df: df.date.apply(lambda row: row.year)))

ordered_cols = [col for col in features_one_line if col[:2] != 'f_'] + [col for col in features_one_line if col.startswith('f_')]

feature_df = features_one_line[ordered_cols]

In [173]:
# Create differential df - this df is the home features - the away features
diff_cols = [col for col in feature_df.columns if col + '_away' in feature_df.columns and col.startswith('f_')]
non_diff_cols = [col for col in feature_df.columns if col not in diff_cols and col[:-5] not in diff_cols]

diff_df = feature_df[non_diff_cols].copy()

for col in diff_cols:
    diff_df[col+'_diff'] = feature_df[col] - feature_df[col+'_away']

# Prep Model

In [177]:
from sklearn import svm, tree, linear_model, neighbors, naive_bayes, ensemble, discriminant_analysis, gaussian_process
# from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score, GridSearchCV, train_test_split
from sklearn.linear_model import LogisticRegressionCV
from sklearn.feature_selection import RFECV
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn import feature_selection
from sklearn import metrics
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
import warnings
warnings.filterwarnings('ignore')

In [190]:
match_results = (home_games[['game_id','pf','pa','margin']]
     .assign(result=lambda df: df.apply(lambda row: 1 if row['pf'] > row['pa'] else 0, axis=1)))

In [191]:
# Merge result column to feature_df
feature_df = pd.merge(diff_df, match_results, on='game_id')

In [193]:
# Create our test and train sets from our afl DataFrame; drop the columns which leak the result, duplicates, and the advanced
# stats which don't have data until 2015

feature_columns = [col for col in feature_df if col.startswith('f_')]

# Create our test set
test_x = feature_df.loc[feature_df.season == 2023, ['game_id'] + feature_columns]
test_y = feature_df.loc[feature_df.season == 2023, 'result']

# Create our train set
X = feature_df.loc[feature_df.season != 2023, ['game_id'] + feature_columns]
y = feature_df.loc[feature_df.season != 2023, 'result']

# Scale features
scaler = StandardScaler()
X[feature_columns] = scaler.fit_transform(X[feature_columns])
test_x[feature_columns] = scaler.transform(test_x[feature_columns])

In [195]:
# Create a list of standard classifiers
classifiers = [
    #Ensemble Methods
    ensemble.AdaBoostClassifier(),
    ensemble.BaggingClassifier(),
    ensemble.ExtraTreesClassifier(),
    ensemble.GradientBoostingClassifier(),
    ensemble.RandomForestClassifier(),

    #Gaussian Processes
    gaussian_process.GaussianProcessClassifier(),

    #GLM
    linear_model.LogisticRegressionCV(),

    #Navies Bayes
    naive_bayes.BernoulliNB(),
    naive_bayes.GaussianNB(),

    #SVM
    svm.SVC(probability=True),
    svm.NuSVC(probability=True),

    #Discriminant Analysis
    discriminant_analysis.LinearDiscriminantAnalysis(),
    discriminant_analysis.QuadraticDiscriminantAnalysis(),

    #xgboost: http://xgboost.readthedocs.io/en/latest/model.html
#     XGBClassifier()    
]

# Define a functiom which finds the best algorithms for our modelling task
def find_best_algorithms(classifier_list, X, y):
    # This function is adapted from https://www.kaggle.com/yassineghouzam/titanic-top-4-with-ensemble-modeling
    # Cross validate model with Kfold stratified cross validation
    kfold = StratifiedKFold(n_splits=5)

    # Grab the cross validation scores for each algorithm
    cv_results = [cross_val_score(classifier, X, y, scoring = "neg_log_loss", cv = kfold) for classifier in classifier_list]
    cv_means = [cv_result.mean() * -1 for cv_result in cv_results]
    cv_std = [cv_result.std() for cv_result in cv_results]
    algorithm_names = [alg.__class__.__name__ for alg in classifiers]

    # Create a DataFrame of all the CV results
    cv_results = pd.DataFrame({
        "Mean Log Loss": cv_means,
        "Log Loss Std": cv_std,
        "Algorithm": algorithm_names
    })

    return cv_results.sort_values(by='Mean Log Loss').reset_index(drop=True)

In [196]:
best_algos = find_best_algorithms(classifiers, X, y)
best_algos

    Mean Log Loss  Log Loss Std                      Algorithm
0        0.596548  1.982324e-02           LogisticRegressionCV
1        0.597511  2.054989e-02     LinearDiscriminantAnalysis
2        0.613771  1.872947e-02           ExtraTreesClassifier
3        0.618793  2.321082e-02         RandomForestClassifier
4        0.680252  3.361816e-03                          NuSVC
5        0.693147  2.384786e-10      GaussianProcessClassifier
6        0.710749  4.715737e-02             AdaBoostClassifier
7        0.743644  1.742168e-01     GradientBoostingClassifier
8        0.798266  8.549817e-02  QuadraticDiscriminantAnalysis
9        0.950008  1.230321e-01              BaggingClassifier
10       1.448459  1.342113e+00                            SVC
11       1.519869  1.189784e-01                    BernoulliNB
12       1.874710  6.489766e-02                     GaussianNB

In [198]:
# Try a logistic regression model and see how it performs in terms of accuracy
kfold = StratifiedKFold(n_splits=5)
cv_scores = cross_val_score(linear_model.LogisticRegressionCV(), X, y, scoring='accuracy', cv=kfold)
cv_scores.mean()

0.6695151262941526

In [199]:
chosen_algorithms = best_algos.loc[best_algos['Mean Log Loss'] < 0.67, 'Algorithm'].tolist()
chosen_algorithms

['LogisticRegressionCV',
 'LinearDiscriminantAnalysis',
 'ExtraTreesClassifier',
 'RandomForestClassifier']

In [200]:
# Define a function which optimises the hyperparameters of our chosen algorithms
def optimise_hyperparameters(train_x, train_y, algorithms, parameters):
    kfold = StratifiedKFold(n_splits=5)
    best_estimators = []

    for alg, params in zip(algorithms, parameters):
        gs = GridSearchCV(alg, param_grid=params, cv=kfold, scoring='neg_log_loss', verbose=1)
        gs.fit(train_x, train_y)
        best_estimators.append(gs.best_estimator_)
    return best_estimators

# Define our parameters to run a grid search over
lr_grid = {
    "C": [0.0001, 0.001, 0.01, 0.05, 0.2, 0.5],
    "solver": ["newton-cg", "lbfgs", "liblinear"]
}

# Add our algorithms and parameters to lists to be used in our function
alg_list = [LogisticRegression()]
param_list = [lr_grid]

In [201]:
# Find the best estimators, then add our other estimators which don't need optimisation
best_estimators = optimise_hyperparameters(X, y, alg_list, param_list)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

In [202]:
lr_best_params = best_estimators[0].get_params()
lr_best_params

{'C': 0.01,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'newton-cg',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [203]:
kfold = StratifiedKFold(n_splits=10)
cv_scores = cross_val_score(linear_model.LogisticRegression(**lr_best_params), X, y, scoring='neg_log_loss', cv=kfold)
cv_scores.mean()

-0.5943621920418511

In [205]:
lr = LogisticRegression(**lr_best_params)
lr.fit(X, y)
final_predictions = lr.predict(test_x)

accuracy = (final_predictions == test_y).mean() * 100

print("Our accuracy in predicting the 2023 season is: {:.2f}%".format(accuracy))

Our accuracy in predicting the 2023 season is: 65.36%

In [218]:
game_ids = test_x[(final_predictions != test_y)].game_id
home_games.loc[home_games.game_id.isin(game_ids), ['date', 'team', 'opponent', 'margin']]

           date team opponent  margin
4463 2023-03-16  RCH      CAR     0.0
4464 2023-03-17  GEE      COL   -22.0
4467 2023-03-18  GCS      SYD   -49.0
4469 2023-03-19  GWS      ADE    16.0
4470 2023-03-19  HAW      ESS   -59.0
4471 2023-03-19  STK      FRE    15.0
4472 2023-03-23  CAR      GEE     8.0
4473 2023-03-24  BRL      MEL    11.0
4474 2023-03-25  COL      POR    71.0
4476 2023-03-25  FRE      NTH    -1.0
4477 2023-03-25  WBD      STK   -51.0
4479 2023-03-26  WCE      GWS    19.0
4485 2023-04-01  POR      ADE   -31.0
4487 2023-04-02  GCS      GEE    19.0
4488 2023-04-02  MEL      SYD    50.0
4490 2023-04-06  BRL      COL    33.0
4492 2023-04-08  ADE      FRE    39.0
4493 2023-04-08  RCH      WBD    -5.0
4494 2023-04-08  SYD      POR    -2.0
4501 2023-04-14  RCH      SYD   -44.0
4503 2023-04-15  ESS      MEL    27.0
4508 2023-04-21  FRE      WBD   -49.0
4513 2023-04-23  CAR      STK   -22.0
4517 2023-04-28  STK      POR    -7.0
4519 2023-04-29  SYD      GWS    -1.0
4524 2023-04-30  RCH      GCS   -24.0
4525 2023-04-30  ADE      COL    -1.0
4526 2023-05-05  CAR      BRL   -26.0
4536 2023-05-12  RCH      GEE    24.0
4537 2023-05-13  SYD      FRE   -17.0
4541 2023-05-13  CAR      WBD   -20.0
4547 2023-05-20  FRE      GEE    29.0
4549 2023-05-20  ESS      RCH     1.0
4554 2023-05-27  STK      HAW   -10.0
4555 2023-05-27  MEL      FRE    -7.0
4556 2023-05-27  GEE      GWS    -7.0
4558 2023-05-27  GCS      WBD     7.0
4561 2023-05-28  ADE      BRL    17.0
4565 2023-06-03  GCS      ADE    25.0
4566 2023-06-03  WBD      GEE   -22.0
4569 2023-06-08  SYD      STK   -14.0
4571 2023-06-10  HAW      BRL    25.0
4573 2023-06-10  FRE      RCH   -15.0
4575 2023-06-11  CAR      ESS   -34.0
4583 2023-06-22  GEE      MEL    15.0
4590 2023-06-30  SYD      GEE     0.0
4593 2023-07-01  GCS      COL   -78.0
4597 2023-07-02  MEL      GWS    -2.0
4598 2023-07-06  RCH      SYD    13.0
4606 2023-07-09  ESS      ADE    18.0
4608 2023-07-14  MEL      BRL     1.0
4611 2023-07-15  CAR      POR    50.0
4612 2023-07-15  ADE      GWS   -14.0

# Prediction Season Results

In [226]:
home_games[home_games['year']==2023].tail(50)

,venue,team,opponent,won,loss,draw,pf,pa,margin,year,round,at_home,date,game_id
4620,Optus Stadium,FRE,SYD,0,1,0,76.0,105.0,-29.0,2023,R19,True,2023-07-22,4621
4621,Adelaide Oval,POR,COL,0,1,0,83.0,85.0,-2.0,2023,R19,True,2023-07-22,4622
4622,Manuka Oval,GWS,GCS,1,0,0,103.0,63.0,40.0,2023,R19,True,2023-07-23,4623
4623,MCG,MEL,ADE,1,0,0,97.0,93.0,4.0,2023,R19,True,2023-07-23,4624
4624,Marvel Stadium,STK,NTH,1,0,0,69.0,61.0,8.0,2023,R19,True,2023-07-23,4625
4625,MCG,COL,CAR,0,0,0,NaN,NaN,NaN,2023,R20,True,2023-07-28,4626
4626,Mars Stadium,WBD,GWS,0,0,0,NaN,NaN,NaN,2023,R20,True,2023-07-29,4627
4627,GMHBA Stadium,GEE,FRE,0,0,0,NaN,NaN,NaN,2023,R20,True,2023-07-29,4628
4628,Heritage Bank Stadium,GCS,BRL,0,0,0,NaN,NaN,NaN,2023,R20,True,2023-07-29,4629
4629,Adelaide Oval,ADE,POR,0,0,0,NaN,NaN,NaN,2023,R20,True,2023-07-29,4630
4630,Marvel Stadium,ESS,SYD,0,0,0,NaN,NaN,NaN,2023,R20,True,2023-07-29,4631
4631,Marvel Stadium,HAW,STK,0,0,0,NaN,NaN,NaN,2023,R20,True,2023-07-30,4632
4632,Optus Stadium,WCE,NTH,0,0,0,NaN,NaN,NaN,2023,R20,True,2023-07-30,4633
4633,MCG,RCH,MEL,0,0,0,NaN,NaN,NaN,2023,R20,True,2023-07-30,4634
4634,Marvel Stadium,WBD,RCH,0,0,0,NaN,NaN,NaN,2023,R21,True,2023-08-04,4635
4635,Adelaide Oval,ADE,GCS,0,0,0,NaN,NaN,NaN,2023,R21,True,2023-08-05,4636
4636,Marvel Stadium,ESS,WCE,0,0,0,NaN,NaN,NaN,2023,R21,True,2023-08-05,4637
4637,MCG,HAW,COL,0,0,0,NaN,NaN,NaN,2023,R21,True,2023-08-05,4638
4638,GMHBA Stadium,GEE,POR,0,0,0,NaN,NaN,NaN,2023,R21,True,2023-08-05,4639
4639,GIANTS Stadium,GWS,SYD,0,0,0,NaN,NaN,NaN,2023,R21,True,2023-08-05,4640
4640,Blundstone Arena,NTH,MEL,0,0,0,NaN,NaN,NaN,2023,R21,True,2023-08-06,4641
4641,Optus Stadium,FRE,BRL,0,0,0,NaN,NaN,NaN,2023,R21,True,2023-08-06,4642
4642,Marvel Stadium,STK,CAR,0,0,0,NaN,NaN,NaN,2023,R21,True,2023-08-06,4643
4643,MCG,COL,GEE,0,0,0,NaN,NaN,NaN,2023,R22,True,2023-08-11,4644
4644,Marvel Stadium,NTH,ESS,0,0,0,NaN,NaN,NaN,2023,R22,True,2023-08-12,4645
4645,SCG,SYD,GCS,0,0,0,NaN,NaN,NaN,2023,R22,True,2023-08-12,4646
4646,Gabba,BRL,ADE,0,0,0,NaN,NaN,NaN,2023,R22,True,2023-08-12,4647
4647,Optus Stadium,WCE,FRE,0,0,0,NaN,NaN,NaN,2023,R22,True,2023-08-12,4648
4648,MCG,CAR,MEL,0,0,0,NaN,NaN,NaN,2023,R22,True,2023-08-12,4649
4649,UTAS Stadium,HAW,WBD,0,0,0,NaN,NaN,NaN,2023,R22,True,2023-08-13,4650
4650,Marvel Stadium,STK,RCH,0,0,0,NaN,NaN,NaN,2023,R22,True,2023-08-13,4651
4651,Adelaide Oval,POR,GWS,0,0,0,NaN,NaN,NaN,2023,R22,True,2023-08-13,4652
4652,Marvel Stadium,COL,BRL,0,0,0,NaN,NaN,NaN,2023,R23,True,2023-08-18,4653
4653,MCG,RCH,NTH,0,0,0,NaN,NaN,NaN,2023,R23,True,2023-08-19,4654
4654,Heritage Bank Stadium,GCS,CAR,0,0,0,NaN,NaN,NaN,2023,R23,True,2023-08-19,4655
4655,GIANTS Stadium,GWS,ESS,0,0,0,NaN,NaN,NaN,2023,R23,True,2023-08-19,4656
4656,Adelaide Oval,ADE,SYD,0,0,0,NaN,NaN,NaN,2023,R23,True,2023-08-19,4657
4657,Marvel Stadium,STK,GEE,0,0,0,NaN,NaN,NaN,2023,R23,True,2023-08-19,4658
4658,Marvel Stadium,WBD,WCE,0,0,0,NaN,NaN,NaN,2023,R23,True,2023-08-20,4659
4659,Optus Stadium,FRE,POR,0,0,0,NaN,NaN,NaN,2023,R23,True,2023-08-20,4660
4660,MCG,MEL,HAW,0,0,0,NaN,NaN,NaN,2023,R23,True,2023-08-20,4661
4661,MCG,ESS,COL,0,0,0,NaN,NaN,NaN,2023,R24,True,2023-08-25,4662
4662,Marvel Stadium,CAR,GWS,0,0,0,NaN,NaN,NaN,2023,R24,True,2023-08-25,4663
4663,Gabba,BRL,STK,0,0,0,NaN,NaN,NaN,2023,R24,True,2023-08-25,4664
4664,Optus Stadium,WCE,ADE,0,0,0,NaN,NaN,NaN,2023,R24,True,2023-08-25,4665
4665,Adelaide Oval,POR,RCH,0,0,0,NaN,NaN,NaN,2023,R24,True,2023-08-25,4666
4666,SCG,SYD,MEL,0,0,0,NaN,NaN,NaN,2023,R24,True,2023-08-25,4667
4667,Blundstone Arena,NTH,GCS,0,0,0,NaN,NaN,NaN,2023,R24,True,2023-08-25,4668
4668,MCG,HAW,FRE,0,0,0,NaN,NaN,NaN,2023,R24,True,2023-08-25,4669
4669,GMHBA Stadium,GEE,WBD,0,0,0,NaN,NaN,NaN,2023,R24,True,2023-08-25,4670